name: CI

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./dashboard

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Install pnpm
      uses: pnpm/action-setup@d15e628ca66d93ee5f352c71671a7bc6a97af5c9 # v6.0.8
      with:
        package_json_file: dashboard/package.json
    - name: Use Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: '22'
        cache: 'pnpm'
        cache-dependency-path: dashboard/pnpm-lock.yaml
    - run: pnpm install --frozen-lockfile
    - run: pnpm run build
