name: deploy to github pages

# on:
#   push:
#     branches:
#       - master
on: [push]

defaults:
  run:
    working-directory: ./graph

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - name: grunt deploy
      run: |
        git config user.name "GitHub Action"
        git config user.email "bot@github.com"
        npx grunt deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
