name: update metrics
on:
  workflow_dispatch:
    inputs:
      weight:
        description: 'Weight metrics on kilogram'
        required: true
      fat:
        description: 'Fat metrics on kilogram'
        required: false
        default: null
jobs:
  update_metrics:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Update jsonl
      run: |
        datetime=`date '+%F %T'`
        fat=${{ github.event.inputs.fat }}
        fat_percent=$((${{ github.event.inputs.fat }} / ${{ github.event.inputs.weight }} * 100 ))
        if [ -z $fat ]; then fat=null ; fi
        echo "{\"datetime\": \"${datetime}\", \"weight\": ${{ github.event.inputs.weight }}, \"fat\": ${fat}}" >> data.jsonl
        # git commit
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update metrics on ${datetime}"
      env:
        TZ: Asia/Tokyo
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Slack Notification on SUCCESS
      if: success()
      uses: tokorom/action-slack-incoming-webhook@main
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        text: Weight updated!
        attachments: |
          [
            {
              "color": "good",
              "author_name": "${{ github.actor }}",
              "author_icon": "${{ github.event.sender.avatar_url }}",
              "fields": [
                {
                  "title": "体重",
                  "value": "${{ github.event.inputs.weight }}"
                },
                {
                  "title": "脂肪 (kg)",
                  "value": "${{ github.event.inputs.fat }}"
                },
                {
                  "title": "体脂肪率 (%)",
                  "value": "${{ fat_percent }}"
                }
              ]
            }
          ]

