name: update metrics
on:
  workflow_dispatch:
    inputs:
      weight:
        description: 'Weight metrics on kilogram'
        required: true
      fat:
        description: 'Fat metrics on kilogram'
        required: false
        default: null
jobs:
  update_metrics:
    runs-on: ubuntu-latest
    steps:
    - name: Update jsonl
      run: |
        datetime=`date '+%F %T'`
        fat=${{ github.event.inputs.fat }}
        if [ -z $fat ]; then fat=null ; fi
        echo "{\"datetime\": \"${datetime}\", \"weight\": ${{ github.event.inputs.weight }}, \"fat\": ${fat} }" >> data.jsonl
      env:
        TZ: Asia/Tokyo


