name: update metrics
on:
  workflow_dispatch:
    weight:
      description: 'Weight metrics on kilogram'
      required: true
    fat:
      description: 'Fat metrics on kilogram'
      required: false
jobs:
  update_metrics:
    runs-on: ubuntu-latest
    steps:
    - run: |
        datetime=`date '+%F +%T'`
        echo "{\"datetime\": \"${datetime}\", \"weight\": ${{ github.event.inputs.weight }}, \"fat\": ${{ github.event.inputs.fat }} }"
      env:
        TZ: Asia/Tokyo


