name: update metrics
on:
  workflow_dispatch:
    inputs:
      weight:
        description: 'Weight metrics on kilogram'
        required: true
      fat:
        description: 'Fat metrics on kilogram'
        required: false
        default: null
jobs:
  update_metrics:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Update jsonl
      run: |
        datetime=`date '+%F %T'`
        fat=${{ github.event.inputs.fat }}
        if [ -z $fat ]; then fat=null ; fi
        echo "{\"datetime\": \"${datetime}\", \"weight\": ${{ github.event.inputs.weight }}, \"fat\": ${fat} }" >> data.jsonl
        # git commit
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update metrics on ${datetime}"
      env:
        TZ: Asia/Tokyo
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}


